### ISSUE TITLE
Machines fuse broke and cannot fix

### ISSUE THREAD

**Issue by Naomi267** [AllTheMods/ATM-8#1030]
Comes up with a prompt saying right click with fresh fuse and I have used a whole stack crafted 3 new ones and nothing is working it's a centrifuge am I doing something wrong or is this a bug ?

**Comment by James103** [comment]
The machine is breaking down because it is receiving power at too high a voltage.
1. Disconnect the power to the machine.
2. Insert transformer upgrades into the machine. For an LV machine (32 EU/t), 1 upgrade = MV (128 EU/t), 2 upgrades = HV (512 EU/t) and 3 upgrades allows the machine to accept EV power (2048 EU/t).
3. Only once the machine has the upgrades should you connect power again.
