### ISSUE TITLE
Ram filling up and crashing 

### ISSUE THREAD

**Issue by Realishbird** [AllTheMods/ATM-8#1094]
Anyone know this issue it just started crashing last night and getting very laggy
https://gyazo.com/b77dde40a579a517aca78388cdc6986a
https://gyazo.com/67836ddf7b5ced6c0f7b6f9ff8b9b880

server has 27gb of ram allocated the server ends up using all of that and some swap mem then crashes 
 
https://mclo.gs/FhhgvnB debug latest 
https://mclo.gs/firhEhW crash log

**Comment by James103** [comment]
Is the server really using all RAM allocated after some time, no matter how much? If so, there is most likely a memory leak somewhere, probably caused by one of the mods in the modpack. Increasing the RAM allocation will only lengthen the amount of time until the server crashes. See also #1073 and #1069.

**Comment by rctcool0** [comment]
I'm currently having server tick issues as well, though I only have 4GB of RAM allocated. Mine is running in a docker image on TrueNAS Scale. According to one of my players, this occurs when trying to open some Lootr chests. Running the latest version, 1.0.14.
