### ISSUE TITLE
1.14 crash logs

### ISSUE THREAD

**Issue by Gumptionless** [AllTheMods/ATM-8#1147]
I dont understand crash logs atall,
if anyone could help this has been plaguing my server since 1.11, ive been stuck playing 1.10

https://pastebin.com/X5RYtH4k

I dont know if more of the log than this is needed, please let me know

**Comment by Mitchell5200** [comment]
okay, that's the particle render crash, we hope to have that fixed in 1.0.15 of the pack that was just released, please give that version a go when it becomes available for you

Duplicate of #923,#930,#933,#943,#944,#949,#959,#980,#985,#988,#990,#993,#999,#1025,#1034,#1036,#1039,#1055,#1059,#1071,#1090

**Comment by Gumptionless** [comment]
thank you for getting back to me so fast,

Glad to know its not something new,
I have tried lowering my particles to minimal but the issue still occurs so hopefully that narrows down what it could be,

Looking forward to 1.0.15
