### ISSUE TITLE
[Bug] Animate Block + Mob Duplicator 

### ISSUE THREAD

**Issue by LamaTheReal** [AllTheMods/ATM-8#1239]
So if you use "Animate Block" from Ars Nouveau and capture it using an mob imprisonment tool and putting it inside a mob duplicator the game crashes and the world is corrupted idk how to fix this and wanted to report it since i love to test stupid stuff on my main world 👍
Version used: ATM8 - 1.0.15

**Comment by MindCaged** [comment]
Good to know since I was thinking about trying this. I'm guessing without knowing the source code, but maybe it's trying to spawn a version of the mob with no block defined since it doesn't keep nbt. I'm not a dev for this mod though. I'm guessing the entity doesn't have a default block to take the form of.

Only solutions I can think of.
1. Restore a backup, simplebackups is in ATM8 and makes one every 2 hours or so.
2. You could try disabling industrial foregoing which would delete any blocks including the mob duplicator, but if the entity it spawned still exists it might still crash. Depends if it crashes before or after it spawned the entity.
3. The same as number 2 but with the ars mod, which would also delete any ars blocks/items you have. Probably more likely to work.
4. Not sure if there's a save editor for 1.19.2 that you could delete just the mob duplicator and any mobs around it, this is a bit advanced though.
5. Wait for the mob author to fix this bug by giving the animated block a failure condition or something for spawning or give it a default appearance.

Frankly, restoring from backup is probably your best bet for the least losses as I'm assuming you probably have a lot of ars and foregoing infrastructure since a mob duplicator takes some work to get, and I think animate block is a tier 2 spell.
