### ISSUE TITLE
Upgraded from 1.0.8 to 1.0.17 - Client Crash "The game crashed whilst rendering overlay"

### ISSUE THREAD

**Issue by JamesArhy** [AllTheMods/ATM-8#1277]
Error:
`The game crashed whilst rendering overlay
Error: com.electronwill.nightconfig.core.io.WritingException: An I/O error occured`

Crash Log:
https://mclo.gs/Y5Nd3vZ

**Comment by A009i8** [comment]
the new update is buggy i think you can play 1.0.15. i have the crash since i update yesterday

**Comment by Mitchell5200** [comment]
> Error: `The game crashed whilst rendering overlay Error: com.electronwill.nightconfig.core.io.WritingException: An I/O error occured`
> 
> Crash Log: https://mclo.gs/Y5Nd3vZ

@JamesArhy looks like another process/program is accessing the client files, locate the program and close it, or just delete the config being accessed and it'll regen on next start
`Caused by: java.nio.file.FileSystemException: C:\Users\********\curseforge\minecraft\Instances\All the Mods 8 - ATM8 (1)\config\cosmeticarmorreworked-common.toml: The process cannot access the file because it is being used by another process`

@A009i8 in what regards?

**Comment by Vinguard** [comment]
I have been having this issue as well since i updated, seems it only happens when im running a server and have the client open as well.

**Comment by JamesArhy** [comment]
Thanks @Mitchell5200 .  I think this has more to do with curseforge being buggy than this modpack.  When I looked in my curseforge app today after rebooting I had two 1.17 instances listed.  Upon removing one instance, I was able to launch just fine.
