### ISSUE TITLE
Minecolonies requesting "structure void"

### ISSUE THREAD

**Issue by Springer250** [AllTheMods/ATM-8#1296]
I've been working with the Shire theme on what is the current latest version (1.0.17) and, when building a residence, it's asking for 2 structure void blocks.  I'm guessing it's a blueprint glitch, but it makes it impossible for the builder to finish.

**Comment by Aligmatism** [comment]
Figure I'd update this ticket since I've come across a similar issue myself. 
MineColonies in the latest version (1.0.19b) is asking me for Barriers in the building resources list.
Hovering over it gives me the description in the attached images.
Builder will not continue or start building if these "resources" aren't given.
More specifically this is an Urban Birch Lvl.1 Fisher's Hut. Have not come across this issue with the Town Hall, Builder's Hut, Tavern, Restaurant or University.
![2023-05-23_22 05 35](https://github.com/AllTheMods/ATM-8/assets/134474096/c7e2dca2-d145-4cb4-a45e-36bf360fed75)
![2023-05-23_22 06 36](https://github.com/AllTheMods/ATM-8/assets/134474096/63b711ae-e6ce-4993-a715-a85d3b399e98)
![2023-05-23_22 16 58](https://github.com/AllTheMods/ATM-8/assets/134474096/03a3a76b-1a75-4c84-929a-01757e1660c5)
![2023-05-23_22 23 52](https://github.com/AllTheMods/ATM-8/assets/134474096/25120c76-ad3a-4ac9-8d22-4d1ccc420048)
