### ISSUE TITLE
Hexerei Dupe bug

### ISSUE THREAD

**Issue by RoyalMink** [AllTheMods/ATM-8#1307]
I came across a Hexerei structure and found a Witch Hazel Drying Rack and accidentally put my Enchanter's Sword into it, and upon breaking the rack to get it out, I found a second in my inventory. Repeating the process again, then with an Enchanter's Mirror, re-logging, and trying again with other items, from vanilla to other mods had the same result.
![dupebug](https://user-images.githubusercontent.com/132167151/235322298-33be53c8-d37f-4751-aa11-6df18c4fe4a7.png)

Nvm, see its already being resolved

**Comment by HumdrumPanic** [comment]
There were a lot of unspecified bugfixes for Hexerei in its version 3.0.

(from hexerei changelog: "Fixed nearly all of the bugs on the bug tracker, so if you run into another unintended bug please put it in the issues.")

Atm 8 1.20 looks to have updated hexerei to 3.2.2... so it may have been fixed with any version past that.

ATM8 still has the temp script installed and recipes locked by default. You can easily disable those yourself by deleting the kubejs scripts in order to test it if you don't want to wait.

Although the recipe lock script for the racks is in the same script file as the securitycraft project dupe bug so you might have to edit out the specific lines for the drying racks as I think the projector is still bugged.
