### ISSUE TITLE
[ATM8 1.0.17] Theurgy Divination Rods Have No Recipe

### ISSUE THREAD

**Issue by conneich** [AllTheMods/ATM-8#1309]
As the title states. I have an Iron Divination Rod that I had made in 1.0.16, I updated to 1.0.17 and now none of the rods have recipes. I checked the changelogs and saw no mention of them being removed.

**Comment by conneich** [comment]
So a quick update. I found that finding the wands in JEI and trying to look at their recipe only shows the enchanting applications it will accept. However, searching for an ingredient of the recipe will show the wand.

**Comment by klikli-dev** [comment]
This is actually a bug in the Theurgy version currently used in ATM 8.
Due to a bug the recipes do not show if some specific mods are loaded alongside Theurgy.
The latest Theurgy version fixes that - in fact, you can update your Theurgy version client-side with the latest jar from CurseForge and it will work (and you can still connect to servers that run an older version of theurgy).
