### ISSUE TITLE
Dsicrimaination against Windows 7 users

### ISSUE THREAD

**Issue by BigRenegade** [AllTheMods/ATM-8#1315]
Since I cannot install CurseForge as the lowlifes no longer have a Windows 7 app I cannot install this modpack so I guess you all want to screw over a lot of players who want to play it but can't because you did not make a mod pack for everyone so screw this modpack

**Comment by V4M0N0S** [comment]
Security updates and technical support for Windows 7 were discontinued on January 14, 2020 after 10 years.

You should definitely upgrade your system. 😆

**Comment by BigRenegade** [comment]
Some of us CANNOT afford $200 for a new version of Windows, so now you are discriminating againt the handicapped/disabled!

    On Monday, May 1, 2023 at 05:56:20 AM EDT, V4M0N0S ***@***.***> wrote:  
 
 


Security updates and technical support for Windows 7 were discontinued on January 14, 2020 after 10 years.

You should definitely upgrade your system. 😆

**Comment by Mitchell5200** [comment]
As per the Microsoft support page, Microsoft has ended support for windows 7, back in 2020. Due to that Curseforge then also has no obligation to create and support a windows 7 compatible launcher. 
Idk why you're complaining to us about it, as there's nothing we can do about it, complain to Curseforge or microsoft, but you'll likely get the same answer as was just given here.
https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962
![Screenshot 2023-05-01 18 02 11](https://user-images.githubusercontent.com/45913837/235438337-787b92f0-1fa6-40c5-9bb5-c436226d7816.png)

**Comment by LimitlessGreen** [comment]
You still can upgrade to win10 with the free Windows 10-Update-Assistent. Or use https://atlasos.net/ if you want a gaming optimized Windows without Microsoft tracking.
