### ISSUE TITLE
Duplication bug between Supplementaries and Sophisticated Backpacks. (1.0.21b)

### ISSUE THREAD

**Issue by YahdaYahda** [AllTheMods/ATM-8#1492]
Right clicking items on stacked sacks stored in a backpack puts that item in all sacks in the stack. Example link: https://www.youtube.com/watch?v=ZMQLGQa1pN8

**Comment by P3pp3rF1y** [comment]
ideally this would be fixed in supplementaries by checking the stack of sacks that is being right clicked and don't allow stashing items if the stack has more than one sack (as other mods that allow stacking sacks can run into the same issue). 
But there's also a `nonStackableItems` config in both backpacks and storage that can prevent them stacking even if the stack upgrades are present
