### ISSUE TITLE
ATM 8 - Exception in server tick loop

### ISSUE THREAD

**Issue by AlabamerHammer** [AllTheMods/ATM-8#1537]
I can't figure out why I get a random crash while exploring

crash report:
[crash-2023-07-07_17.57.37-server.txt](https://github.com/AllTheMods/ATM-8/files/11986547/crash-2023-07-07_17.57.37-server.txt)

**Comment by Averymon** [comment]
I get the same issue with a certain players base, we cant figure out what item/mod is causing it. I've had a ticket in for multiple weeks and have heard nothing.

**Comment by LukeOnuke** [comment]
the thing that solved it was removing catwalk stairs, but it was the stupidest issue ive seen. It would only crash if you walk on them. So i asked the dude to remove the stairs, and it worked. The server no longer crashed. Also we removed the copycat walls from create because those kinds of blocks have always messed with my worlds.

**Comment by Averymon** [comment]
Glad you found your solution. No one on my server uses those :(

**Comment by LukeOnuke** [comment]
f
