### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid

### ISSUE THREAD

**Issue by ReivaxMirkys** [AllTheMods/ATM-8#1654]
My game crash when I try to join it. I could play yesterday and I change nothing in the Nether (where the problem seem to be)
[crash-2023-08-18_15.53.19-server.txt](https://github.com/AllTheMods/ATM-8/files/12380124/crash-2023-08-18_15.53.19-server.txt)

**Comment by TigerWalts** [comment]
This is a known bug with Hose Pulleys placed on a chunk edge: https://github.com/Creators-of-Create/Create/issues/4987

Depending on the order the chunks are loaded/unloaded the Hose Pully may try to get block data from a chunk that is currently unloaded. - Fixed in Create 0.5.1c.

---

Only fix is to remove the hose pulley either by having a player approach it from a direction that loads chunks neighbouring the chunk with the pully first or by editing the world save data with an NBT editor.

An alternate fix is to edit the FTB Chunks save data to force load all the neighbouring chunks.
