### ISSUE TITLE
ATM 8 Map won't open

### ISSUE THREAD

**Issue by HunterXd2904** [AllTheMods/ATM-8#1655]
I'm playing ATM 8 with a friend in a LAN words has been some weeks, but has been some days that de mod just stop working. I open de mod and when i try do open de word it load until 100% and nothin happens. The game don't crash or stop responding, it just wont open the word, I try wait to see if its just take a while because the map its very big at this point, but i waited ate least one hour and nothing happened. The more weird is every time i use a backup from the easy backups folder the map open, than after close the map it stop launching again. I tried fix the instalation in forge and alocate more memory (its with 20 Gb of ram, and i tried put less as i see that too much ram may cause problems). The problem seem to be in the map as other maps opens, the only explanation I thought ist because ta map its too big (about 4 Gb right now). If someone know how to fix this problem pls help, its too annoying have to lose progress every time by having to use a backup bacause of this.

**Comment by camp00000** [comment]
If you have an AE2 or refined storage system and store a lot of items with a ton of NBT data in there it might be corrupting your save.

If you're not doing that it may still be something else that's continuously running and corrupting your world forcing you to reset to a "good save" every so often. Debugging this is probably quite a headache but if you upload the logs (use pastebin.com or similar) and post them here that'd definitely help trying to identify the issue because the issue description alone won't suffice.
