### ISSUE TITLE
pneumaticcraft gasoline not working with thermal expansion compression dynamo

### ISSUE THREAD

**Issue by noleosis** [AllTheMods/ATM-8#1681]
Title about sums it up. I've tried multiple different methods of extracting and inserting the fluid from a tank and into the dynamo but it doesn't work. I mean the fluid will not even go into the dynamo let alone actually use it as fuel.

**Comment by camp00000** [comment]
Make sure the gasoline accepted by the dynamo is actually the one from pneumaticcraft because there's a few overlapping oil/gasoline fluids from different mods if I remember correctly.

If that's not an issue, see if you can get any other fluid into it which should work according to docs/JEI, if not, there may be some other underlying issue at hand.

**Comment by noleosis** [comment]
It looks as though pneumaticcraft fluids are not usable in advanced generators or by thermal expantion at all. Although the fluids do work for create's fluid blaze burner and a couple of them for ad astra, which I would guess is intended. I'm not sure what to make of it really.
