### ISSUE TITLE
Sophisticated Backpacks or Sorting mod bug

### ISSUE THREAD

**Issue by nexuspro21** [AllTheMods/ATM-8#169]
When you sort items in sophisticated backpack they sometimes "duplicate" (it deletes some items ie. diamonds, iron, cobblestone etc.) non stackable items ie. apotheosis gems or sword, armor piece, it happens at random

**Comment by JustLuckyJohn** [comment]
I noticed this too. I came to the conclusion it might be because of the lollipops you get from Corail tombstone halloween event. I had no issues with my backpack prior to the event. But during the event I saw alot of stuff getting duplicated and some stuff randomly disappearing. My solution was to blacklist every lollipop from ever entering into my backpack. Voiding the lollipops seemed to have the same effect of duplication and disappearing of items. I would suggest making it so that the backpack never picks up any of these event lollipops. I hope they will stop dropping after halloween, cause I already hate them with great passion.

**Comment by P3pp3rF1y** [comment]
I made a fix for those like 2 days ago which however was related to them crashing the game when they were picked up / put in backpack some other way. But anyway seeing that ATM 8 was last updated before that fix it would make sense to grab it first and retest with it.
