### ISSUE TITLE
[0.1.7] Internal Server Error (Disconnect to main menu) Bug Caused by Lollipop (Corail Tombstone) when eaten by Advanced Feeding Upgrade (Sophisticated Backpacks)

### ISSUE THREAD

**Issue by HaylingZar** [AllTheMods/ATM-8#176]
The steps to reproduce this error are as follows:

- Connect to a server
- Place lollipops from Corail Tombstone mod into backpack (Sophisticated Storage mod)
- Socket backpack with Advanced Feeding Upgrade
- Client will crash to the main menu randomly when a lollipop item is consumed.
- Error message will read: "Disconnected: Internal Server Error". 
- Upon reconnecting, the issue will be resolved (eating another lollipop will have a chance for the issue to reoccur).

**Comment by JustLuckyJohn** [comment]
There is most likely a conflict with Sophisticated Storage and Corail Tombstone halloween event. I had no problems prior to the event. As soon as Lollipops was placed in Sophisticated backpack inventory, noticed items got duplicated and some items disappearing completely, even voiding items would give the same results. Better of putting the lollipop in the blacklist, so that the backpack doesn't pick them up, if you are using the magnet and not putting any in the backpack.

**Comment by Mitchell5200** [comment]
fixed by backpacks dev
