### ISSUE TITLE
Stone shovel recipe not working

### ISSUE THREAD

**Issue by Chrizzzmo** [AllTheMods/ATM-8#177]
Every time i try to craft stone shovel using cobble stone blocks it won't craft due to being the same as Stone Sword. and it doesn't matter what kind of stone I use they all end up making the sword. I've tried restarting game, and it will always happen.

This stops progress in the beginning for the quest book

**Comment by JustLuckyJohn** [comment]
A quick manual fix in-game, open up the mod list (can be set to keybind in keybinds:open mod list). Search for Quark. Press Quark and then config. Press tweaks. Got to the bottom to Utility Recipes, press the pen icon. Uncheck the button (so that it is a red X) for "Better Stone Tool crafting". After that press, done and then done, so that you are back to the config screen for Quark. Now press "Save changes". 

If you still can craft, open up command (press T) and type /reload. And let the game reload. It will take some time until you can use the crafting table. But once it has reloaded, you should be able to craft a shovel. I did this for my singleplayer game.

**Comment by Chrizzzmo** [comment]
Thank you! It immediately was fixed after trying your guide :)
