### ISSUE TITLE
Hopper dont work on Composter

### ISSUE THREAD

**Issue by LadyHerbstwald** [AllTheMods/ATM-8#198]
Hello unfortunately the hopper cannot put the wheat seeds (or other seeds) into the composter.
Would be grateful for help

**Comment by Jorue23** [comment]
Schreib es bitte auf Englisch

**Comment by LadyHerbstwald** [comment]
Hello unfortunately the hopper cannot put the wheat seeds (or other seeds) into the composter.
Would be grateful for help

**Comment by DarkPhoenix1512** [comment]
Ja Lady schon besser ups hier noch die EN version: Yes Lady already better

**Comment by Jorue23** [comment]
Dude if you want to get any help here at least write in the appropriate language cause else almost nobody can understand you.

**Comment by alex123abc15** [comment]
The issue is with the [canary mod](https://github.com/AbdElAziz333/Canary) the mod [changed how hoppers work](https://github.com/AbdElAziz333/Canary/blob/mc1.19.2/architectury_forge_loom/src/main/java/com/abdelaziz/canary/mixin/block/hopper/README.md) for optimization. To fix this you need to change the `canary.properties` file in the config folder and add the line `mixin.block.hopper=false`. This happens with hoppers interacting with lots of modded items including the [little logistics chest cars](https://github.com/MuradAkh/LittleLogistics).
