### ISSUE TITLE
Quark Stoneling Generation Causes Major Lag

### ISSUE THREAD

**Issue by rk** [AllTheMods/ATM-8#243]
Hi, I'm running a server and seeing some big, incidental lag spikes when a Stoneling generates. From what I've seen in these two profiler traces, the cause looks like the loot table. Was that modified by ATM8? I'm not sure if I should cross-post to the Quark issues.

Trace 1: https://spark.lucko.me/eDQZTQKzPh
Trace 2: https://spark.lucko.me/IKIVPeuHQM

I do have armor with multiple Luck levels on it, from Apotheosis. Which could maybe be amplifying the loot generation issue.

**Comment by ward-hop** [comment]
I'm seeing the same thing on a custom modpack with similar mods, and this post is the only mention of it I can find. Similar trace results which point to `vazkii.quark.content.mobs.entity.Stoneling.finalizeSpawn()` Also running in an environment where complex lootgen could be making the issue worse.

**Comment by FinityKing** [comment]
I found that the loot the stoneling drops is what causes the problem, before the glimmering weald was introduced the stonelings didn't cause problem's but ever since that update they now drop maps that guide you to the weald, so everytime they drop the map upon death huge lag spikes occur. 
You can disable them from dropping the maps in the configs.
