### ISSUE TITLE
Minecolonies Not Working

### ISSUE THREAD

**Issue by Tiny-Person** [AllTheMods/ATM-8#26]
For some reason, there is no tape that usually goes around the selected building area. This results in the minecolonist to not build any of the buildings as well as not list any of the supplies they need. I've tried it multiple times, in a server than in a single-player world, and it hasn't worked. 
I forgot to mention this, but it only spawns in one npc instead of the usual 4.

**Comment by Fuechslein** [comment]
From the minecolonies discord:

_If you are playing ATM8, and experiencing issues with a builder who isn't building, or a builder stuck or not not moving, etc., the issue is with the config. Right now the AI Update rate is set to 100(defaults to 1) which makes them take hours to think, change the line in the config manually to 1 for now. I also recommend changing the builder block placement delay back down to default from 250._

Serverconfig is in your world folder.

**Comment by Tiny-Person** [comment]
> 

Thank you! It's working now :D
