### ISSUE TITLE
Randomized sweeping edge/crits with swords

### ISSUE THREAD

**Issue by Wairpre** [AllTheMods/ATM-8#271]
An unknown mod setting forces swords to randomly crit/sweeping edge regardless of the original vanilla mechanics. This causes some mob farms to overload with mobs, especially with Apotheosis modified spawners. Is there a way to revert this mechanic to vanilla mechanics?

**Comment by James103** [comment]
Caused by the Apotheosis mod.
The mod adds an attribute "Crit Chance" which defaults to 50%, meaning all hits that would otherwise not be critical have a 50% chance of being counted as a critical chance.

To reduce this, run the following command each time you respawn: `attribute @s apotheosis:crit_chance base set 1`, where a value of 1 means 0% Crit Chance, 1.3 is 30% Crit Chance, 1.5 is 50% Crit Chance (default), and 2 is 100% Crit Chance.
