### ISSUE TITLE
Server lag spikes - help

### ISSUE THREAD

**Issue by bomber1992** [AllTheMods/ATM-8#276]
Hey I'm currently having problems that my server is quite laggy and wanted to ask what I could change

Dedicated Rootserver

I7 - 6700K
64GB DDR4
1 Gbit Up/Down
NVMe - Write : 2,960 Mbit/s Read : 3,180 Mbit/s 

Sparkprofiler Log : https://spark.lucko.me/3b9zj2Vjs9

My JVM Flags 

-Xms10G
-Xmx30G
-XX:+UseG1GC
-XX:+ParallelRefProcEnabled
-XX:MaxGCPauseMillis=200
-XX:+UnlockExperimentalVMOptions
-XX:+DisableExplicitGC
-XX:+AlwaysPreTouch
-XX:G1NewSizePercent=40
-XX:G1MaxNewSizePercent=50
-XX:G1HeapRegionSize=32M
-XX:G1ReservePercent=20
-XX:G1HeapWastePercent=5
-XX:G1MixedGCCountTarget=4
-XX:InitiatingHeapOccupancyPercent=20
-XX:G1MixedGCLiveThresholdPercent=90
-XX:G1RSetUpdatingPauseTimePercent=5
-XX:SurvivorRatio=32
-XX:+PerfDisableSharedMem
-XX:MaxTenuringThreshold=1

**Comment by Lvcx01** [comment]
same problem, but with a 10900k, 32gb ram

**Comment by jbagwell27** [comment]
I'm having the same problem, too even after several updates. V1.0.10. and but it's been lagging since day one. The one probe will randomly say waiting for server, and whenever I travel I lag and end up getting "teleported" backwards.
I have given the server 32gb ram and minecraft is given 30 of it.  
It's got 12 cores, and it's in the closet next to me.

**Comment by SkyKingPX** [comment]
Why. My Minecraft got 6GB and the Server 12GB RAM. And its working pretty good

**Comment by jbagwell27** [comment]
I actually figured it out. Server-side view distance. I changed that to 6 from default 12 and it fixed it
