### ISSUE TITLE
Framed block crash

### ISSUE THREAD

**Issue by L0NL3Y-50UL** [AllTheMods/ATM-8#293]
If you use a copper block on a fancy framed rail, fancy framed rain slope, or any of the variants. It causes a full crash on the players side, servers fine. 
Possibly unrelated the chunks that this occurred in got corrupted and needed to be reset.

Best Regards
P.S. Your breathtaking

**Comment by XFactHD** [comment]
This is the second time I am hearing about a crash related to the new fancy rails but I have yet to get an actually useful log to find out what's going on.
Please put the client's debug log from the crash on https://gist.github.com/ and post the link here (you may have to enable the debug log in the CurseForge settings first and then re-create the crash). The crash report is of no use in this case.

**Comment by L0NL3Y-50UL** [comment]
https://gist.github.com/L0NL3Y-50UL/dd6f2d1123abd36b5b0c1ce6ac329df5

**Comment by XFactHD** [comment]
That crash-report unfortunately has nothing to do with this issue. Coincidentally I managed to recreate the issue you encountered though and I'm testing the fix right now, so a full log is very likely not needed anymore.

**Comment by L0NL3Y-50UL** [comment]
Alrighty then thank you for the hard work and sorry for the inconvenience

**Comment by XFactHD** [comment]
The fix for this issue is available now as of FramedBlocks 6.6.2 for 1.19 and 5.9.2 for 1.18. You can manually update your client to the respective version until a pack update includes the fix.

Also, to clear up potential confusion, this is a purely client-side issue and does not corrupt the chunk in any way, it simply prevents you from viewing the chunk.
