### ISSUE TITLE
Framed Slab Crash

### ISSUE THREAD

**Issue by WaRAnAfB** [AllTheMods/ATM-8#297]
I tried to put a frame slab on the block below a slab feeder from the productive bees mod and my client crashed. Apparently the server is fine, but I can't log in since the game crashed. I tried to replicate this problem on a local world and got the same result. Something similar with this issue https://github.com/AllTheMods/ATM-8/issues/293

**Comment by Mitchell5200** [comment]
Did you try to update the mod as the mod author suggested?

**Comment by WaRAnAfB** [comment]
Yes, I did but the problem persists
[crash-2022-11-19_07.31.57-client.txt](https://github.com/AllTheMods/ATM-8/files/10047201/crash-2022-11-19_07.31.57-client.txt)

**Comment by XFactHD** [comment]
This is an issue with ProductiveBees. They are trying to set a BlockState property that doesn't exist on Framed Slabs. I assume they are expecting all blocks in the slabs tag to behave the exact same way as vanilla slabs, which is not possible in the case of Framed Slabs.

**Comment by WaRAnAfB** [comment]
So for now all we have to do is wait for that fix. is it so?

**Comment by XFactHD** [comment]
The crash report gives you the location of the block, so you could try to use the setblock command (assuming you are an OP) to replace the block with air. The block position in the crash report is as follows: `Block location: World: (263,66,-577)`.
Otherwise you could try to edit the chunk with external software or wait for the fix. The ProductiveBees devs are already informed and working on it.

**Comment by JaisDK** [comment]
PB updated with a fix
