### ISSUE TITLE
Refined Storage Mod extreme laggs, when show recipe while in Crafting Grid 

### ISSUE THREAD

**Issue by MineCherry** [AllTheMods/ATM-8#389]
should be a bug from Refined Storage. 
f.e. go in crafting grid, search in Jei garden gloche and u got 3 Fps or intense game freeze for about 1 minute.
do the same with vanilla crafting table causes no issues.

testet with 2 other players, maybe move to Moddev

**Comment by Mitchell5200** [comment]
Yeah it's a known RS issue (of many), i don't think it has a chance of getting fixed however, as the mod dev is working on RS2 and RS1 is in maintenance mode at this stage.

The only fix i have is to use AE2 instead.

**Comment by k1ll3rrs** [comment]
Whenever you open a recipe inside the (Refined Storage) the Game crashes, and now that I simply have thousands of items, it never unlocks. I SUGGEST removing this MOD, because eventually some player in the group will use it.
---------------------
Sempre que abre uma receita dentro do (Refined Storage) o Jogo trava , e agora que tenho milhares de itens simplesmente, nunca destrava. SUGIRO removedor este MOD, pois eventualmente algum player do grupo, vai usar.

**Comment by alfredggttv** [comment]
ATM8 v1.0.7 includes the updated version.
