### ISSUE TITLE
(Hopping) Botany pots not working for any kind of seed or sapling in v0.0.11

### ISSUE THREAD

**Issue by niggelasso** [AllTheMods/ATM-8#41]
In version 0.0.11, the botany pot do not have any sort of capability of housing the seeds of Mystical Agriculture or even the normal Minecraft tree saplings. Hope for a workaround in the next versions 😄

**Comment by indygwyn** [comment]
Mods: Botany Pots/Botany Trees
Issue: Botany Pots not working with all seeds/saplings

Tested:
- Integrated Dynamics Menril Saplings
- Croptopia Seeds
- Silent Gear Flax Seeds
- Immersive Engineering Hemp Seeds
- Blue Skies Seeds

**Comment by indygwyn** [comment]
Looks like mod author is looking at adding Croptopia support
https://github.com/Darkhax-Minecraft/BotanyPots/issues/240

**Comment by Darkhax** [comment]
Hello, author here. 

All of the Mystical Agriculture seeds and soils are already supported and have been since before this issue was created. Make sure you're using the right soil as they only grow in Mystical Agriculture's special farmland by default. I can only add support for crops available in standalone mods, so if a modpack has created their own custom crop variants they should also be adding the compat files to make it work with Botany Pots. 

Trees are added via a separate mod called [Botany Trees](https://www.curseforge.com/minecraft/mc-mods/botany-trees). It's not in the base mod because the focus of my mod is crops and I don't want to step on the toes of the Bonsai Trees dev. Ideally I think modpacks should use both Bonsai Trees and Botany Pots together, however I know that some packs prefer a unified system which is why I still offer tree support. 

The other seeds and saplings you mentioned are likely not supported yet. A datapack file needs to be created for each plant that can grow in the pot. While modpack authors can define crops themselves using datapacks and scripts it would be better for the community if non-custom crops were supported in the base mod. I am only one person and often unfamiliar with the various mods so any help from the community in supporting additional crops is appreciated.

**Comment by Mitchell5200** [comment]
Most Botany trees support has been added, more will be added in the future, Closing for now

**Comment by Zhirsh** [comment]
Menril trees not working properly in pots. Work-around, take the trees out and replant every so often resets their timers? noit sure. Cheers.
