### ISSUE TITLE
dimension Card bug

### ISSUE THREAD

**Issue by AdamGG9666** [AllTheMods/ATM-8#458]
When I put my dimension card into a wireless transmitter the whole system just shots down until I take out the card. I tried it with the advanced wireless transmitter too but the card just simply doesn't work that way

**Comment by James103** [comment]
Check the power coming in to the controller in your AE2 or Refined Storage system where you're trying to use the dimension card in.

If you have a Refined Storage system, make sure you're providing the controller with more than 8 kFE/t since the Dimension Card uses that much power.

If you have an AE2 system, make sure you're providing it with enough power and that there is at least a Dense Energy Cell attached to the network.

**Comment by SasNos** [comment]
Same headline, different behaviour.

In my case the Creative Wireless Crafting Grid is not working with the Dimension Card. I can access the inventory, but readonly. So I cannot add or remove items to the storage network.

**Comment by Kapuupa** [comment]
I have the same problem as AdamGG9666 but even when I see that my system is down I can still acces my network with creative universal wireless crafting grid. And I know that I have enough power because I use ultimate universal cable (that is connected to a induction cell multiblock from Mekanism) and the energy inside the controller is always full. Btw I use refined storage

**Comment by SasNos** [comment]
Update: I can access my network now. I believe I couldn't access it before because the chunks where my network was set up were not force-loaded via FTB ^^ Works perfectly fine in any dimension now!

**Comment by Kapuupa** [comment]
Update: I found out that if you RS system uses more than 16k/t then it will shutdown. I increased the controller's energy storage from 32k to 64k and now it works for me. I think that if your RS system uses more than half of controller's energy storage per tick then it will shutdown. I didn't test it but that's my conclusion.

**Comment by 1337Mishka** [comment]
Seems to be a chunk loading issue just like SasNos described. Thats what fixed it for me at least.
