### ISSUE TITLE
Settings Reset on restart

### ISSUE THREAD

**Issue by powerman984** [AllTheMods/ATM-8#496]
After restarting the game all sound and some video settings reset such as Fullscreen and vsync

**Comment by TheAngryFire** [comment]
Had the same issue... disabling the defaultsettings mod resolved this for me. Not sure why it was not working as expected..

**Comment by SSkizz** [comment]
> Had the same issue... disabling the defaultsettings mod resolved this for me. Not sure why it was not working as expected..

Hmm, tried this and still having same issue. Strange.

**Comment by zl03134** [comment]
met too need help

**Comment by zl03134** [comment]
set "options.txt" read-only After finish configuration **temporarily**

**Comment by SSkizz** [comment]
> set "options.txt" read-only After finish configuration **temporary way**

Oh right... duh 🤦‍♂️
The simplest temp fixes always seem to pass by me haha, thanks.

**Comment by westriel** [comment]
Has there been any update to this? I'm running my own dedicated server for a few friends and we want to change the spice of life setting but anytime I change the solcarrot-server.toml in the world folder it gets reverted and the solcarrot-server.toml in default settings appears to be ignored. Any advice? I can't disable the default settings mod because that mod isn't a server mod so its not in the server's files
