### ISSUE TITLE
Whole chunk lightning becomes dark after a server restart

### ISSUE THREAD

**Issue by Nasuw** [AllTheMods/ATM-8#525]
I'm getting a problem with the chunks I put my machines on (don't know if it is a part of the problem), it becomes dark after a server restart, looks to be server-sided since my friend has the same problem.
My wind Generators show "Sky Blocked" as there were blocks above but there's clearly nothing above.

Thanks in advance !

![01 lightning](https://user-images.githubusercontent.com/62486798/209550704-b5701b44-cd1f-4054-a676-55960dabd6a3.png)
![02 lightning](https://user-images.githubusercontent.com/62486798/209550706-f04f2e75-fa93-439f-8579-735b35fd009c.png)

**Comment by Mitchell5200** [comment]
I currently don't know what's causing this, but another player in the discord found the solution from a vanilla 1.14 bug report, the link below links to that report, a fix is posted there
https://bugs.mojang.com/browse/MC-142134
Screenshot attached too
![Screenshot 2022-12-26 23 59 51](https://user-images.githubusercontent.com/45913837/209565888-8c0d27f9-c185-4aaf-a78e-3663dd41f2de.png)

**Comment by redrafa** [comment]
Something else is also tripping it because some light emitting blocks/entities are also turned to 0 even though they are on/activated.

**Comment by DerTyp876** [comment]
I have the same issue after almost every server restart, and not just in one chunk.
It's very annoying since monsters spawn and farmland gets destroyed
![2023-01-29_21 07 33](https://user-images.githubusercontent.com/76851529/215353191-1f56dae9-038e-437a-a808-11b581ae7ea4.png)
![2023-01-29_21 07 24](https://user-images.githubusercontent.com/76851529/215353197-1b28c588-4f05-4f64-9a0b-a1f96baf8ff0.png)

**Comment by Yobwan** [comment]
I'm also having the lighting issue, it seems to follow my mekanism machines around (I've moved the machines and different chunks experience this issue) and eventually spreads to other chunks. The erase cache is only a temporary fix and can be done in game through the optimize world feature. I have to do that before every game, else it gets worse. It spreads to other chunks any time the game is loaded (after initially launching the game after the cache fix) and every time I jump between the nether and back to the regular world.

**Comment by Mitchell5200** [comment]
tracked at https://github.com/JoeFoxe/Hexerei-1.18/issues/79
duplicate of #525, #724, #791

**Comment by IMaxwellI** [comment]
Hi. I have the same issue but found it to be a different block from a different mod.
On my server, the logic cable from IntegratedDynamics is causing it.
The bug happens when you connect the cable to something.

My example: I wanted to run my sophisticated storage with a controller and terminal from Integrated Dynamics. For that you need to connect an Item Interfact to the Controller, a logic cable on top and add the terminal to that. Only the logic cable created the issue.

After removing all logic cables:
The light level 0 isn't the whole chunk. It ends at a certain Y level. Find that level and build a 16x16 plattform into the sky and remove that again. That way the server updates the light again and it's fixed.

**Comment by alexschrod** [comment]
@IMaxwellI Hey, I'm having the same problem and I'm observing the same thing where when I remove the logic cables, then save and load the world, lighting is back to normal, and placing the cables back down, saving and loading again makes the lighting broken again.

> The light level 0 isn't the whole chunk. It ends at a certain Y level. Find that level and build a 16x16 plattform into the sky and remove that again. That way the server updates the light again and it's fixed.

I want to try your fix, but I don't quite understand what you're saying. How do I "find that level?" And do you build a 16x16 only at that level or all the way up from ground to that level, or?

**Comment by IMaxwellI** [comment]
@alexschrod Hi!>

My "fix" won't work for you, as you said
> "then save and load the world, lighting is back to normal"
because for me, that is not the case.
The light stays broken after a restart and that is what my fix is for.

I now just put all my done factory stuff into a single chunk, so I don't have to go in there again :D
The weird thing for me is, that many describe the same issue we have, but with Hexerei. That mod works perfectly fine for me.
So I am wondering what the internals of this issue are... While I hope somebody finds a fix soon, this Issue seems to be present throughout many different MC versions and more than one mod.

**Comment by IMaxwellI** [comment]
I have found a temporary workaround.

When you get the lightbug, as mentioned above, you can build up to the Y level where it's light again, build a plane on that level in the whole chunk and destroy that again. That will fix the light bug. But it will return, when the chunk get's reloaded.

To prevent the chunk from reloading, set the chunk to force loaded with e.g. FTB Chunks. That way, the lighting bug will not return until you either unload the chunk or restart the server.

So if you restart, rinse and repeat.

**Comment by DarkJune0122** [comment]
Was a persistent solution provided for this issue? Building a plane of blocks high up is tedious, to say the least, with multiple broken chunks

**Comment by IMaxwellI** [comment]
> Was a persistent solution provided for this issue? Building a plane of blocks high up is tedious, to say the least, with multiple broken chunks

If the issue still persists, then I guess no.
My "fix" was to put all machines into as few chunks as possible and force loading them.

But ultimately, I switched to ATM9 and ATM10. ATM8 is not getting updates anymore.
