### ISSUE TITLE
Supplementaries crashes the game when naming a new world

### ISSUE THREAD

**Issue by TwiningShiningDawn** [AllTheMods/ATM-8#636]
I tried creating a new world, it crashed to the desktop, i innstalled "Not Enough Crashes (Forge)" so i could see what mod did it without being kicked out of minecraft, and it says Supplementaries
[crash-2023-01-10_13.13.25-client.txt](https://github.com/AllTheMods/ATM-8/files/10385653/crash-2023-01-10_13.13.25-client.txt)

**Comment by Kyzoku** [comment]
I experienced this same issue.

**Comment by e-SonOfAnder** [comment]
Yes, this happens if you hit the button assigned to the Quiver Arrow select key from the key binds at any point during the Minecraft menus. The version of Supplementaries needs to be updated to the current one for this modpack. (Came here to create an issue with them for this exact reason after speaking with the Supplementaries mod author.) 

Reference from the Supplementaries Github: https://github.com/MehVahdJukaar/Supplementaries/issues/490#issuecomment-1396401706 

Do not update to the most current version of the mod, as there is some incompatibility between it and one of his other mods (the Model Gap Fix mod). If you update to version 2.2.35t of Supplementaries, it fixes this issue, and does not appear to introduce new issues.

**Comment by Mitchell5200** [comment]
mod will be updated next release

**Comment by Mitchell5200** [comment]
Fixed in 1.0.9
