### ISSUE TITLE
Chest Recipe 

### ISSUE THREAD

**Issue by NamelessGamer06** [AllTheMods/ATM-8#648]
just wanted to let you know, on the latest ver of ATM 8 via curseforge launcher there is no recipe to craft chests via the tag wood. 
this means I cant craft a chest out of modded wood without the mod having a recipe for it. for base game wood, quark adds a recipe for chests so that works at least.

**Comment by jawbos** [comment]
ATM8 v1.0.8

When selecting the generic minecraft Chest from JEI, the standard minecraft recipe using 8 planks does not show.
Instead a recipe by 'Ars Nouveau' and a recipe by 'Quark' are only displayed. Both of which show they are crafted using a Chest from their respective Mods rather than planks.

If you manually create a chest from 8 planks of wood in a crafting table, instead of receiving a 'Minecraft' Chest, you receive a Chest from 'Quark'.

You must then place the Quark Chest into a crafting table to turn it into the generic Minecraft Chest.

**Comment by Mitchell5200** [comment]
Fixed in 1.0.9
