### ISSUE TITLE
Middle Mouse Inventory Sort

### ISSUE THREAD

**Issue by MyNameIsChrissy** [AllTheMods/ATM-8#694]
When using AE terminals and pressing middle mouse to request a craft it also sorts the inventory and armor ends up in the crafting square along with other weird shenanigans. All inventory sort options are disabled in my controls and searching through mod configs turns up nothing. If I could just know what mod sorts the inventory on middle mouse click so I could disable it that would be great.

**Comment by Mihoshika** [comment]
Same issue here. Disabled all the things in controls using middle mouse, still happening.

**Comment by Mihoshika** [comment]
Think I found it. It's Inventory Profiles Next. I think the hotkey for sorting inventory is bound to mouse wheel?

**Comment by dypo** [comment]
> Think I found it. It's Inventory Profiles Next. I think the hotkey for sorting inventory is bound to mouse wheel? Not 100% certain, since its default seems to be R, but I think that was the mod.

Can confirm that this is the cause. In-game, go to Mod Options > Inventory Profiles Next > Config > Hotkeys, and you can change the Sort Inventory hotkey there. I set it to R and now I can click Middle Mouse Button in a AE2 UI without my armor teleporting to random slots in my inventory.

**Comment by FlightXCaptain** [comment]
Hi Guys. i have the same issue but i have no Inventory Profile option under mod options...

**Comment by necauqua** [comment]
Hi, on 1.0.15 if you open the universal AE2 terminal (the `de.mari_023.ae2wtlib.wct.WCTScreen` thing), switch the current terminal to pattern-encoding one and try to change the amount with middle-click, it puts a random stack into your hand - including sometimes the entangled singularity which breaks the connection 🤷

It's because it opens the vanilla-appeng `appeng.client.gui.me.items.SetProcessingPatternAmount` screen, for which the IPN was not blocked.

For once the anoying `r g` keybind (to fix that) was useful :sweat_smile:

**Comment by zur1801** [comment]
> For once the anoying `r g` keybind (to fix that) was useful

Is there a way to disable this?
I don't even know what mod it's from.

**Comment by Mitchell5200** [comment]
Inventory Profiles Next
https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next
