### ISSUE TITLE
Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by FooterMan15** [AllTheMods/ATM-8#751]
After crashing repeatedly for unknown reasons, I checked out all my crash reports, and it appears the mod "EvilCraft" is having trouble rendering blood splashes...? I'm not exactly sure how to read crash logs properly, but that's what it looks like. I was going to post on their github, but they say to report it here first.

Here's the latest one: https://gist.github.com/FooterMan14/37f1eba0e6bcbe874a94ef6cfd4a94bc
Crashing on 1.0.8 / 1.0.9, I haven't played older versions.

**Comment by Mitchell5200** [comment]
Okay cool, we suspected there were other mods that were causing the issue, can you please add the below mod to you mods folder replacing the existing version there, and then load your game, once you crash, can you post your Latest log back here via https://mclo.gs/ please
Don't worry about the validity of this file, we got it from the mod dev for that mod (XFactHD) via discord as it has some extra logging code for us to be able to debug this issue
[FramedBlocks-6.7.1.zip](https://github.com/AllTheMods/ATM-8/files/10491397/FramedBlocks-6.7.1.zip)

**Comment by FooterMan14** [comment]
Yup, I'll work on that.

**Comment by FooterMan14** [comment]
We still working on this?

**Comment by Mitchell5200** [comment]
> We still working on this?

yes, sorry, we had a bit of a discussion in dev channels with some modders and looked at some logs that some other users provided, and have traced it back to Evilcraft again, despite the dev of that claiming otherwise. information has been passed on to them and hopefully they'll have it fixed soon
https://github.com/CyclopsMC/EvilCraft/issues/961#issuecomment-1403884727
