### ISSUE TITLE
[Suggestion] Refined Storage Controller power buffer increase

### ISSUE THREAD

**Issue by PikachuGabe** [AllTheMods/ATM-8#763]
If possible, increasing the power buffer on Refined Storage's Controller would be VERY helpful and fix a major issue: limiting how much you can use a mod. RS doesn't have subnetworks or the ability to have multiple controllers, so if your power usage goes over a certain margin your controller will be turning on and off every tick. This would fix the issue.

Video of me experiencing the issue described in version 1.0.9 

https://user-images.githubusercontent.com/84477180/214457536-b94fe14c-53ce-4fa8-bdc1-f4dbd7234445.mp4

**Comment by James103** [comment]
How much power is your system using?
Assuming the relevant config option is default (which it should be in this pack), if your Refined Storage system uses greater than 16 kFE/t, it will shut down (intermittently or fully) regardless of the amount of power your RS controller is receiving.

**Comment by PikachuGabe** [comment]
It was using around 16k rf/t. That config sounds annoying.

**Comment by IkarosXenano** [comment]
I've also been having the same problem, I just go into the config and changed both the cap to 64kfe and just changed the usage of the RSInfinity Booster upgrades like the Dimensional and Infinity range boosters down to like 1kfe. Because those 2 together take up like 12kfe together. 

And it's pretty easy to configure them, you can do it from in game and just change the values to whatever you want, may have to restart your game or exit your world to see the changes though

**Comment by James103** [comment]
> Because those 2 together take up like 12kfe together

You can take out the infinity range booster card and keep only the Dimension Card and still have infinite wireless range in all dimensions at a power cost of only 8 kFE/t, as the Dimension Card includes the effects of the infinity range booster.

**Comment by PikachuGabe** [comment]
> Assuming the relevant config option is default (which it should be in this pack), if your Refined Storage system uses greater than 16 kFE/t, it will shut down (intermittently or fully) regardless of the amount of power your RS controller is receiving.

looked through the configs,thats just straight up not a thing.

**Comment by enigmaquip** [comment]
> looked through the configs,thats just straight up not a thing.

Sure it is. `<world folder>/serverconfig/refinedstorage-server.toml`

**Comment by PikachuGabe** [comment]
> Sure it is. `<world folder>/serverconfig/refinedstorage-server.toml`

what line then? i couldnt find anything that states if it maxes it out at a certain rf usage no matter what.

**Comment by James103** [comment]
In the Refined Storage config's `[controller]` section:
`capacity` is the maximum amount of energy (in FE) the controller can store (normally 32000 FE).
`maxTransfer` is the maximum amount of power (in FE/t) the controller can receive (normally 2<sup>31</sup>-1 FE/t)

If the system uses more FE/t than the lesser of (half of `capacity`) and `maxTransfer`, the system will shut down due to insufficient power. In the former case (system uses more FE/t than half the controller's battery), the controller itself will light up but the rest of the system will be offline.

Most likely the controller **is** displayed as receiving enough power, but due to some intricacies in how Refined Storage uses energy, the system thinks it does not have enough power to continue operating and shuts down.

**Comment by EinApfel1** [comment]
Thank you @James103 took me some hours to even find the error, using the mod Cable Tiers my server always crashed if i added one more thing to the system :D 
Thank god these servers don´t take forever to reboot ;)
