### ISSUE TITLE
Ars Conflict

### ISSUE THREAD

**Issue by CelticKnot13** [AllTheMods/ATM-8#951]
There seems to be an Ars N. conflict that's not allowing the worn notebook to load
![2023-02-23_23 57 21](https://user-images.githubusercontent.com/126227854/221103410-33553352-2c6b-43eb-ac5c-cc5539295865.png)

Any information would be appreciated!

**Comment by StyxSouls** [comment]
I'm assuming you're on a server because Ars Elemental for the client download of ATM8 on CurseForge is using a different version compared to the server files download.

The client is on 5.8.0 and the server files have 5.7.6 so for a quick fix just update the server files to have Ars Elemental 5.8.0.

(At least this is the same issue I had and that's how I fixed it)

**Comment by CelticKnot13** [comment]
Sorry for the delay, Baby was just born the other day lol

That worked! Just deleted the old Jar file and got the updated one that matched the client side and added it to the server files and restarted the server. I appreciate the help!
