### ISSUE TITLE
Mekanism pipe contents not visable

### ISSUE THREAD

**Issue by Kyuketsuki57** [AllTheMods/ATM-8#957]
Cannot see comtents of pipes in mekanism for liquids, gases or items. However can see the contents of power cables 
![PXL_20230225_134255839](https://user-images.githubusercontent.com/126243082/221360164-d9a2b424-8078-444b-9aa3-4663d4d0aade.jpg)
Not sure if this is a mekanism bug or the one probe

**Comment by Kyuketsuki57** [comment]
![Uploading PXL_20230225_134320529.jpg…]()

**Comment by Kyuketsuki57** [comment]
![PXL_20230225_134320529](https://user-images.githubusercontent.com/126243082/221360292-4d889e5b-9f10-450e-b9b7-30e4c46c2854.jpg)

**Comment by James103** [comment]
According to The One Probe configuration file that ships with this modpack, you need to be holding / wearing the probe item in order to view these contents, as they are considered "extended info" in the mod. Changing the 3 to a 0 at the end of the following line should suffice:
https://github.com/AllTheMods/ATM-8/blob/d42420b46af7faff54e4ffb01293a08a4c61cd4e/config/theoneprobe-common.toml#L6

**Comment by Kyuketsuki57** [comment]
So I did this and it still didn't work, but using "the one probe" in game item "" the one probe read me" I was able to fix this. Thank you :)
