### ISSUE TITLE
Server Crashes when trying to generate the end/nether

### ISSUE THREAD

**Issue by LateAndon** [AllTheMods/ATM-8#995]
ATM8 1.0.13

Every time myself or other players on the server try to use a nether portal or end portal the server times you out, then crashes.

https://mclo.gs/Pssz2Bm

**Comment by tuxedorose1011** [comment]
I also have this issue. The server tic takes too long and then the server crashes due to the tic taking too long

**Comment by GillesMommerency** [comment]
Same for me

**Comment by tomasdavies1605** [comment]
Also having this issue!

**Comment by TheSpy0** [comment]
Same problem with ATM8 1.0.13. Running the server in a container. Below is the crash report.

[crash-2023-03-04_23.18.40-server.txt](https://github.com/AllTheMods/ATM-8/files/10889889/crash-2023-03-04_23.18.40-server.txt)

**Comment by tomasdavies1605** [comment]
I managed to find a sort of a fix, my issue was only with The End but I have a feeling that's because I had already entered the Nether before the most recent update.

I copied the server seed and used that make a single player world. The portal I was trying to use on the server was still broken and caused a crash so I went to another one and it worked. I then copied the DIM1 folder into from the single player world into the server and I can now load in fine in the server and so can other players!

I also saw another post which suggested taking off any extended items, so I took my backpack off before going too and just used a scroll to get home after arriving!

Hope that helps!

**Comment by tuxedorose1011** [comment]
That worked for me! I copied my world onto my local computer, and entered the nether, then copy and pasted the DIM folders back to the server. I did have to tp out of the nether for it to successfully load in single player though because I was falling through the ground, probably because the load was a little slow.

So short summary on what I did
1. copy world from server
2. enter nether in single player
3. teleport out of the nether once in
4. copy nether folder (DIM folder) back to server.

**Comment by MRFriday96** [comment]
> That worked for me! I copied my world onto my local computer, and entered the nether, then copy and pasted the DIM folders back to the server. I did have to tp out of the nether for it to successfully load in single player though because I was falling through the ground, probably because the load was a little slow.
> 
> So short summary on what I did
> 
> 1. copy world from server
> 2. enter nether in single player
> 3. teleport out of the nether once in
> 4. copy nether folder (DIM folder) back to server.

This worked for me. TY

**Comment by Mitchell5200** [comment]
I have traced a cause the the mod "when Dungeons arise" (DungeonsArise-1.19.2-2.1.54-release.jar), the exact reason as to why is still under investigation, but for now you can safely remove the mod from your servers with no other issues.
Further investigation is ongoing as to why, before reporting to the WDA devs

**Comment by embeddedt** [comment]
Hello, this is a drive-by comment, but by taking a look at the linked crash reports I have noticed that in both cases one worker thread seems to be busy running DFU logic:

Attached crash file in https://github.com/AllTheMods/ATM-8/issues/995#issuecomment-1454923722:
```
"Worker-Main3" daemon prio=1 Id=83 RUNNABLE
	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.datafixers.FunctionType$$Lambda$50760/0x0000000805b84a30.apply(Unknown Source)
	at java.base@19.0.2/java.util.function.Function.lambda$compose$0(Unknown Source)
	at java.base@19.0.2/java.util.function.Function$$Lambda$12204/0x0000000801f45800.apply(Unknown Source)
	at java.base@19.0.2/java.util.function.Function.lambda$compose$0(Unknown Source)
	at java.base@19.0.2/java.util.function.Function$$Lambda$12204/0x0000000801f45800.apply(Unknown Source)
	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.datafixers.FunctionType$$Lambda$50760/0x0000000805b84a30.apply(Unknown Source)
	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.datafixers.FunctionType$Instance.lambda$first$1(FunctionType.java:81)
	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.datafixers.FunctionType$Instance$$Lambda$50764/0x0000000805b88248.apply(Unknown Source)
	...
```

A nearly identical stacktrace can be seen by searching for `Worker-Main2` in the original crash report in the top post.

Many mods ship outdated structure files from previous Minecraft versions which means that the game needs to run them through DFU whenever they are generated. The upgraded version is also not saved and reused so this process is repeated each time the file is loaded. It is quite possible that the game is simply taking over 60 seconds to complete this process, as DFU is very slow.

(Also, from anecdotal experience, I have seen outdated Dungeons Arise structures being used in the overworld, so I suspect the nether/end have similar problems.)

**Comment by 0x78f1935** [comment]
I was able to join the end after numerous server crashes after I executed the following command in game:
```
/forge generate 0 60 0 100 minecraft:the_end
```

Now this problem seems to happen once entering the portal after defeating the ender dragon.
I'm not sure what the name is of this world,.. is it minecraft:the_end_2 or something?

**Comment by embeddedt** [comment]
This makes sense to me; if Forge does pregeneration on a background thread then all of the slow upgrading will not cause the server thread to block, and therefore prevent the watchdog from being triggered.
